"""recriando tabelas

Revision ID: 0e36b3bb6ed8
Revises: f4e8b5790d74
Create Date: 2025-12-01 03:23:46.868279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e36b3bb6ed8'
down_revision: Union[str, Sequence[str], None] = 'f4e8b5790d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
