"""add lgpd and roles

Revision ID: 1667394ff851
Revises: caf021483b38
Create Date: 2025-12-01 22:32:42.503224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1667394ff851'
down_revision: Union[str, Sequence[str], None] = 'caf021483b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('is_provider_setup', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_contractor_setup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_contractor_setup')
    op.drop_column('users', 'is_provider_setup')
    op.drop_column('users', 'accepted_at')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
